version: '3.1'
services:
  web:
    image: odoo:13.0
    depends_on:
      - postgres
    ports:
      - 8069:8069
    environment:
      - USER=odoo
      - PASSWORD=odoo
      - HOST=postgres
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    networks:
      - icwebapp_network

  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - icwebapp_network
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=test_odoo@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres_passwd    
    networks:
      - icwebapp_network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ${PWD}/servers.json:/pgadmin4/servers.json
  
  ic-webapp:
    image: lsniryniry/ic-webapp:1.0
    ports:
      - 8080:8080
    environment:
      - ODOO_URL=http://localhost:8069   #ici c'est le meme port  dans le service odoo
      - PGADMIN_URL=http://localhost:5432   #ici c'est le meme port  dans le service pgadmin
    networks:
      - icwebapp_network


volumes:
  odoo-web-data:
  odoo-db-data:
  pgadmin-data:

networks:
  icwebapp_network: