version: '3.1'
services:
  odoo:
    image: odoo:13.0
    depends_on:
      - db
    ports:
      - 8069:8069
    container_name: odoo
    environment:
      - USER=odoo
      - PASSWORD=odoo
      - HOST=postgres
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    networks:
      - network_odoo

  db:
    image: postgres:13
    ports:
      - 5432:5432
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - network_odoo
volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  network_odoo:  