version: '3.1'
services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL = "test_odoo@gmail.com"
      - PGADMIN_DEFAULT_PASSWORD = "postgres_passwd"    
    networks:
      - network_pgadmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ${PWD}/servers.json:/pgadmin4/servers.json
  
volumes:
  pgadmin-data:

networks:
  network_pgadmin: