apiVersion: v1
kind: Service
metadata:
  name: pgadminsvc
  labels:
    name: pgadmin
    environment: production
  namespace: icgroup
spec:
  Type: NodePort
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 50
      nodePort: 30050