apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    name: postgres
    environment: production
  namespace: icgroup
spec:
  clusterIP: None
  selector:
    app: postgres
    tier: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432