apiVersion: v1
kind: Service
metadata:
  name: odoosvc
  labels:
    name: odoo
    environment: production
  namespace: icgroup
spec:
  Type: LoadBalancer
  selector:
    app: odoo
    tier: frontend
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069